spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp
#spring.mvc.resources.mapping="/resources/**"
#spring.mvc.resources.location="/resources/"

#Logging
logging.level.org.springframework.web:DEBUG

#Server Port
server.port=8088

#Google Cloud

spring.cloud.gcp.sql.database-name=carwashmanagement
spring.cloud.gcp.sql.instance-connection-name=cosmic-flux-257116:us-central1:adg96307

# So app starts despite "table already exists" errors.
spring.datasource.continue-on-error=true
# Enforces database initialization
spring.datasource.initialization-mode=always

# Leave empty for root, uncomment and fill out if you specified a user
#spring.datasource.username=

# Uncomment if root password is specified
spring.datasource.password=D2016cisuh19

spring.cloud.gcp.project-id=cosmic-flux-257116
spring.cloud.gcp.credentials.location=file:cosmic-flux-257116-464e846b2b8a.json

#Database Connection
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#spring.datasource.url=jdbc:mysql://psd179513.mysql.database.azure.com:3306/zoomanagement?createDatabaseIfNotExist=true&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
#spring.datasource.username=psd179513@psd179513
#spring.datasource.password=P@$$w0rd
spring.data.jpa.repositories.enabled=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false